server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.3.66:3306/oh_coupon
    username: root
    password: rootFwtai
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info