serviceprovider : http://192.168.3.108:8080
server:
  port: 8082
  servlet:
    session:
      cookie:
        name: UISESSIONCOUPON
security:
  oauth2:
    client:
      client-id: CouponSystem
      client-secret: 12345
      access-token-uri: ${serviceprovider}/oauth/token
      user-authorization-uri: ${serviceprovider}/oauth/authorize
    resource:
      #访问‘认证中心’的 com.fwtai.controller.UserController的接口
      user-info-uri: ${serviceprovider}/user/info
logging:
  level:
    root: info
spring:
  thymeleaf:
    cache: false
  security:
    user:
      name: coupon
      password: GZSyinlz1024^*